conference.accu.org/themes/accuconf/less/custom.less, conference.accu.org/themes/accuconf/templates/base.tmpl
Hi,
This includes a few fixes for three column formats. This works only for desktops and large screens. This commit will break rendering on mobiles and tablets. This will be resolved for hand helds once we decide on  how to render the display in those devices. Thanks
=> Fixes for three column format

conference.accu.org/themes/accuconf/less/custom.less, conference.accu.org/themes/accuconf/templates/base.tmpl
On wide screens:
Left column: Navigation links
Right column: Key Dates, Sponsors, Committee information
Middle column: Contents
On Mobiles and tablets:
Navigation links
Key Dates
Content
Sponsors
Committee
=> The layout has been updated for all devices

conference.accu.org/themes/accuconf/less/custom.less, conference.accu.org/themes/accuconf/templates/accuconf.tmpl, conference.accu.org/themes/accuconf/templates/base.tmpl, conference.accu.org/themes/accuconf/templates/base_helper.tmpl
Made the accuconf specific part into a separate template with macros so that we can reuse the same in the dynamic site as well.
=> Created a separate accuconf template for macros

static_nikola_part/posts/201610202151_petriconi_CallForSessions.adoc
Please read the text carefully, because I am not a English native speaker.
At some places are ??? because I did not know the dates.
=> Adding draft for call for papers

flask_application_part/accuconf/proposals/templates/register.html
Nielsen Norman Group: Placeholders in Form Fields Are Harmful ;)
https://www.nngroup.com/articles/form-design-placeholders/
=> Change contact to phone, text to number as placeholder

.travis.yml, flask_application_part/tests/test_submit_proposal.py
This seems a nicer way of handling the testing to me, since it appears to be more PyTest idiomatic. If this works for people I can change the pother tests.
=> Switch from class-based to function-based PyTest usage

flask_application_part/tests/common.py, flask_application_part/tests/nikola_test_index.html, flask_application_part/tests/test_authentication.py, flask_application_part/tests/test_getting_werkzeug_test_client.py, flask_application_part/tests/test_proposal_models.py, flask_application_part/tests/test_registrations.py, flask_application_part/tests/test_submit_proposal.py, flask_application_part/tests/test_user_models.py
The tests have been refactored to put them in idiomatic PyTest format and do some extraction of code into functions to make the tests easier to read and write.
=> Refactored the tests

flask_application_part/accuconf/proposals/utils/database.py, flask_application_part/accuconf/proposals/views.py, flask_application_part/accuconf_config.py, flask_application_part/tests/common.py, flask_application_part/tests/test_registrations.py
=> Various trivial changes.

flask_application_part/accuconf/proposals/templates/base.html, flask_application_part/accuconf/proposals/templates/registration_failure.html, flask_application_part/accuconf/proposals/templates/submission_success.html, flask_application_part/accuconf/proposals/templates/view_proposal.html, flask_application_part/accuconf/templates/base.html
@FelixPetriconi submitted pull request #59 with changes aimed at fixing issue #48 . There were some faults with the pull request as was. Rather than go back and forth to fix them, this pull request replaces that one, includes the good changes from the original avoids the not good ones, and adds a few extras inspired by the originals.
=> A set of changes based on pull request #59

flask_application_part/accuconf/proposals/templates/register.html
Renamed the button to "Reset" since that makes more sense.
=> Rename the "Cancel" button to "Reset"

flask_application_part/accuconf/models/user.py, flask_application_part/accuconf/proposals/templates/base.html, flask_application_part/accuconf/proposals/templates/view_proposal.html, flask_application_part/accuconf/proposals/views.py, flask_application_part/tests/test_submit_proposal.py, static_nikola_part/themes/accuconf/assets/js/accuconf.js
With this PR it is possible to submit more than one proposal.
As well all available proposals can be displayed.
=> Change to fix #49

flask_application_part/accuconf/proposals/templates/submit_proposal.html, flask_application_part/accuconf/proposals/views.py, static_nikola_part/themes/accuconf/assets/js/accuconf.js
This is a simple solution to indicate the user that his/her proposal was accepted.
This make the proposal_success.html template even more useless. But I kept it, because it might be used in a later version.
My goal was here to do a quick improvement.
=> Change to fix #51

flask_application_part/accuconf/proposals/templates/view_proposal.html, flask_application_part/accuconf/proposals/views.py
Please find attached a fix for the merge conflict that causes the My Proposal page to display with an error
=> Fix for merge conflict for Issue 65

flask_application_part/accuconf/__init__.py, flask_application_part/accuconf/models/proposal.py, flask_application_part/accuconf/models/user.py, flask_application_part/accuconf/proposals/templates/login.html, flask_application_part/accuconf/proposals/templates/maintenance.html, flask_application_part/accuconf/proposals/templates/not_logged_in.html, flask_application_part/accuconf/proposals/templates/proposals_base.html, flask_application_part/accuconf/proposals/templates/register.html, flask_application_part/accuconf/proposals/templates/registration_failure.html, flask_application_part/accuconf/proposals/templates/registration_success.html, flask_application_part/accuconf/proposals/templates/review_proposal.html, flask_application_part/accuconf/proposals/templates/review_success.html, flask_application_part/accuconf/proposals/templates/submission_success.html, flask_application_part/accuconf/proposals/templates/submit_proposal.html, flask_application_part/accuconf/proposals/templates/view_proposal.html, flask_application_part/accuconf/proposals/utils/proposals.py, flask_application_part/accuconf/proposals/utils/validator.py, flask_application_part/accuconf/proposals/views.py, flask_application_part/accuconf_config.py, flask_application_part/tests/common.py, flask_application_part/tests/test_authentication.py, flask_application_part/tests/test_proposal_models.py, flask_application_part/tests/test_registrations.py, flask_application_part/tests/test_submit_proposal.py, flask_application_part/tests/test_user_models.py, static_nikola_part/posts/201610202151_callForSessions.adoc, static_nikola_part/themes/accuconf/assets/js/accuconf.js
The changes associated with changing the schema for registration so as to capture the full postal address and a biography.
A whole slew of other changes as well.
=> Registration change

static_nikola_part/conf.py
=> Set the base URL to the actual URL so the RSS feed is correct.

flask_application_part/accuconf/proposals/templates/register.html, flask_application_part/accuconf/proposals/views.py
Adding functionality to edit the users account information
=> Fix#78 and Fix#35

flask_application_part/accuconf/proposals/templates/review_proposal.html, flask_application_part/accuconf/proposals/views.py
Find attached a PR that adds the bio field to the reviewing part.
=> #87 Adding the bio field on the reviewing page

flask_application_part/accuconf/proposals/templates/base.html, flask_application_part/accuconf/proposals/templates/proposals_base.html
=> #89 Fixing tab icon

flask_application_part/emailouts/empty_bio/query.py, flask_application_part/emailouts/empty_bio/subject.txt, flask_application_part/emailouts/empty_bio/text.txt, flask_application_part/emailouts/testing/query.py, flask_application_part/emailouts/testing/subject.txt, flask_application_part/emailouts/testing/text.txt, flask_application_part/scripts/email_people.py
This script takes some mailshot data and creates a mailshot. Currently this uses an SMTP server that only Russel Winder can use. This must be parameterised so others can send mailshots.
The mailshot data in this pull request is for the email to prompt registered people with no bio to add a bio.
=> The script and data that sent the "no bio" email.

Deployment.adoc
We have a document on "How to Start" which is about setting up the local environment for people to develop the Flask application and add to the Nikola material. It seemed appropriate to add to this a document discussing how to deploy the material to the test and live server. This document is the beginnings. It will need ongoing addition and amendment. As will the "How to Start" document.
=> Begin to document the deployment activity.

static_nikola_part/posts/201611060816_websiteProblems.adoc, static_nikola_part/posts/201611161708_callForSessionsExtension.adoc
Revert the recent change to one of the blog entries, and add an update to a different one.
=> Revert a change add another

flask_application_part/accuconf/proposals/templates/register.html, flask_application_part/accuconf/proposals/templates/review_proposal.html, flask_application_part/accuconf/proposals/templates/view_proposal.html
Some of the titles were displayed only too short. With this improvement they should at least as wide as the textfields below.
=> Some text improvements

flask_application_part/accuconf/proposals/templates/proposals_base.html
Fixes Issue #86. Opens Issue #99.
=> Add the links to the Flask template from the Nikola template.

flask_application_part/accuconf/proposals/templates/proposals_base.html, static_nikola_part/themes/accuconf/templates/base.tmpl, static_nikola_part/themes/accuconf/templates/base_helper.tmpl
This fixes Issue #98.
Also add Emacs annotations to ensure Jinja2 mode.
=> Fix the URL under the ACCU 2017 Logo

flask_application_part/accuconf/proposals/templates/review_proposal.html
With this enhancements the buttons on the proposals review page use the same style as the other buttons of the site
=> Use styles for review buttons

flask_application_part/accuconf/proposals/templates/review_proposal.html, flask_application_part/accuconf/proposals/templates/submit_proposal.html
Change according to Jon's and Charles' proposal
=> Renaming the 90 minute interactive session to 90 minute session

flask_application_part/accuconf/proposals/views.py
Please find attached a way to limit submitting a session by the end date. Currently I assume that the server is located somewhere with current date === GMT
The place for the global variable is not optimal, but I don't know a better way of adding it.
=> Adding limitation for submitting proposals by date

flask_application_part/scripts/cli_commands.py
With the web application a single assignment system, system administrator has to fix any proposal text replacements.
=> Add a proposal abstract replacement command.

flask_application_part/accuconf/configuration.py, flask_application_part/accuconf/proposals/views.py
Amend the various configurations. Amend the way the dynamic menu is constructed. Add a new route, but without content as yet.
=> Update the configuration and menu codes.

flask_application_part/accuconf/models/admin.py, flask_application_part/accuconf/proposals/utils/proposals.py, flask_application_part/accuconf/proposals/utils/schedule.py, flask_application_part/tests_selenium/common.py, flask_application_part/tests_selenium/test_registration.py
Changes to the models trying to get the Flask-Admin admin interface to work. It is failing, so abandon for the moment as the data can be amended using sqlitebrowser (albeit not ideal), and time is pressing.
Initial attempts to get some end-to-end tests working using Selenium and PhantomJS.
=> Two things: admin interface and Selenium/PhantomJS tests

flask_application_part/accuconf/models/proposal.py, flask_application_part/accuconf/proposals/views.py, flask_application_part/tests/test_proposal_models.py, flask_application_part/tests/test_submit_proposal.py
Use association objects directly since association proxies didn't seem to work.
=> Amend data model to correct use of is_lead.

flask_application_part/accuconf/configuration.py, flask_application_part/accuconf/proposals/views.py
This is a simple but, for the purposes of the Elm app, mostly adequate JSON API for fetching proposals.
We still need to consider the overall deployment picture for the app. Depending on how we set things up, we may have to look at proper CORS support for this endpoint.
=> JSON API for fetching proposals

static_nikola_part/posts/201704191942_scheduleApp.adoc
I figured the app's blog post could do with a link to the repo.
=> Added link to project repo in Elm app post.

static_nikola_part/stories/2017/schedule.adoc
Added links to YouTube videos to the schedule page of the ACCU 2017 conference.
=> Added links to videos.

pages/2017/schedule.adoc
Add all links to available slides
=> Adding links to available slides

pages/2018/schedule.adoc
Added links to the videos available so far.
Also corrected a few broken links to slide PDFs.
=> Video and slide links

themes/accuconf/templates/accuconf.tmpl, themes/accuconf/templates/base.tmpl
and some source code formatting cleanup
=> Adding the prices back

pages/2019/presenters.adoc, pages/2019/schedule.adoc, pages/2019/sessions.adoc, themes/accuconf/templates/accuconf.tmpl
Sorting the other sponsors alphabetically
Adding Arjan as speaker for the workshop
=> Adding headline sponsor section

pages/2019/presenters.adoc, pages/2019/schedule.adoc, pages/2019/sessions.adoc
There do seem to be more changes here than perhaps there ought to be, but it all looks right.
=> Various changes, including Thomas Guest and Herb Sutter changes.

pages/index.adoc, pages/suggestions.adoc
After my question on accu-general for suggestions for sight seeing around the conference I thought those suggestions might be useful to others too suggesting to store them somewhere.
I added a page for that to the conference website and asked Alan if I could mention his name.
Feel free to correct/extend, hopefully there will be more suggestions until the conference starts. I'm willing to create new pull requests for those if needed.
=> Add a suggestions page
